config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :sites
  resources :demand_sites
  resources :supply_sites
  resources :translinks

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match 'translinks/optimize', :to => 'translinks#optimize'
  match 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  match 'translinks/delete_solution', :to => 'translinks#delete_solution'

end

app/models/supply_site.rb
class SupplySite < ActiveRecord::Base
  attr_accessible :supply_quantity, :site_id
  validates :supply_quantity, :numericality => { :greater_than => 0}

  belongs_to :site
  has_many :translinks, :dependent => :destroy

  def supply_site_codename
    self.site.codename
  end
end

app/controllers/supply_sites_controller.rb
class SupplySitesController < ApplicationController

    before_filter :signed_in_user

    def new
      @supply_site = SupplySite.new
    end

    def index
      @supply_sites = SupplySite.all
    end

    def update
      @supply_site = SupplySite.find(params[:id])

      if @supply_site.update_attributes(params[:supply_site])
        flash[:success] = "Update successful!"
        redirect_to(supply_sites_path)
      else
        render 'edit'
      end
    end

    def destroy
      @supply_site = SupplySite.find(params[:id])
      @supply_site.destroy
      flash[:success] = "Supply Site destroyed."
      redirect_to supply_sites_path
    end

    def edit
      @supply_site = SupplySite.find(params[:id])
    end

    def show
      @supply_site = SupplySite.find(params[:id])
    end

    def create
      @supply_site = SupplySite.new(params[:supply_site])

      if @supply_site.save
        flash[:success] = "Supply Site saved!"
        redirect_to supply_sites_path
      else
        render 'new'
      end
    end

    private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Bitte melden Sie sich an."
      end
    end

end

app/helpers/supply_sites_helper.rb
module SupplySitesHelper
end

app/views/supply_sites/_form.html.erb
<div class="row">
  <div class="span6 offset3">
<%= form_for(@supply_site) do |f| %>
    <% if @supply_site.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@supply_site.errors.count, "error") %> prohibited this supply site from being saved:</h2>

          <ul>
            <% @supply_site.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field selectbox">
      <%= f.label 'Select Code' %><br />
      <%= f.collection_select :site_id, Site.all, :id, :codename %>
    </div>
    <div class="field">
      <%= f.label 'Supply Quantity' %><br />
      <%= f.text_field :supply_quantity %>
    </div>
    <div class="actions">
      <%= f.submit "Save Supply Side" %>
    </div>
<% end %>
  </div>
</div>


app/views/supply_sites/edit.html.erb
<h1>Update Supply Site</h1>

<%= render 'form' %>

<%= link_to 'Show', @supply_site %><br><br>
<%= link_to 'Back', supply_sites_path %>

app/views/supply_sites/index.html.erb
<h1>Data of Supply Sites</h1>

<table class="table">
  <tr>
    <th>Code</th>
    <th>Site</th>
    <th>Supply Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @supply_sites.each do |supply_site| %>
      <tr>
        <td><%= supply_site.site.codename %></td>
        <td><%= supply_site.site.name %></td>
        <td><%= supply_site.supply_quantity %></td>
        <td><%= link_to 'Show', supply_site %></td>
        <td><%= link_to 'Change', edit_supply_site_path(supply_site) %></td>
        <td><%= link_to 'Destroy', supply_site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Supply Site', new_supply_site_path %><br>  <br>
<%= link_to 'Back', current_user %>

app/views/supply_sites/new.html.erb
<h1>New Supply Site</h1>

<%= render 'form' %>

<%= link_to 'Back', supply_sites_path %>

app/views/supply_sites/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <b>Supply Site:</b>
  <%= @supply_site.site.name %>
</p>

<p>
  <b>Supply Quantity:</b>
  <%= @supply_site.supply_quantity %>
</p>

<%= link_to 'Change', edit_supply_site_path(@supply_site) %> <br><br>
<%= link_to 'Back', supply_sites_path %>