config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :sites
  resources :demand_sites
  resources :supply_sites
  resources :translinks

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match 'translinks/optimize', :to => 'translinks#optimize'
  match 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  match 'translinks/delete_solution', :to => 'translinks#delete_solution'

end

app/models/translink.rb
# == Schema Information
#
# Table name: translinks
#
#  id                 :integer          not null, primary key
#  supplysite_id      :integer
#  demandsite_id      :integer
#  unit_cost          :float
#  transport_quantity :float
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Translink < ActiveRecord::Base
  attr_accessible :demand_site_id, :supply_site_id, :transport_quantity, :unit_cost
  validates :transport_quantity, :numericality => { :greater_than_or_equal_to => 0}
  validates :unit_cost, :numericality => { :greater_than_or_equal_to => 0}

  belongs_to :supply_site
  belongs_to :demand_site
end

app/controllers/translinks_controller.rb
class TranslinksController < ApplicationController

  before_filter :signed_in_user

  def new
    @translink = Translink.new
  end

  def show
      @translink = Translink.find(params[:id])
      @supply_site_name = SupplySite.find_by_id(@translink.supply_site_id).site.name
      @demand_site_name = DemandSite.find_by_id(@translink.demand_site_id).site.name
  end


  def create
    @translink = Translink.new(params[:translink])
    @translink.transport_quantity = 0.0
    if @translink.save
      flash[:success] = "Translink saved!"
      redirect_to(translinks_url)
    else
      render 'new'
    end
  end

  def edit
    @translink = Translink.find(params[:id])
  end

  def update
    @translink = Translink.find(params[:id])

    if @translink.update_attributes(params[:translink])
      flash[:success] = "Update successful!"
      redirect_to(translinks_url)
    else
      render 'edit'
    end
  end

  def destroy
    @translink = Translink.find(params[:id])
    @translink.destroy
    flash[:success] = "Translink destroyed."
    redirect_to(translinks_url)
  end

  def index
    @translinks = Translink.all
  end

  def delete_solution

    if File.exist?("Transportmengen_v2.txt")
      File.delete("Transportmengen_v2.txt")
    end

    @translinks = Translink.all
    @translinks.each { |li|
      li.transport_quantity=0.0
      li.save
    }
    @objective_function_value=nil
    flash[:success] = "Solution destroyed!"
    redirect_to current_user
  end



  def optimize
    if File.exist?("Transportmodell_v3_Input_Instanz1.inc")
      File.delete("Transportmodell_v3_Input_Instanz1.inc")
    end

    f=File.new("Transportmodell_v3_Input_Instanz1.inc", "w")

    printf(f, "set i / \n")
    @supply_sites = SupplySite.all
    @supply_sites.each { |ssi| printf(f, "i" + ssi.id.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "j / \n")
    @demand_sites = DemandSite.all
    @demand_sites.each { |dsi| printf(f, "j" + dsi.id.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "l / \n")
    @translinks = Translink.all
    @translinks.each { |li| printf(f, "l" + li.id.to_s + "\n") }
    printf(f, "/;" + "\n\n")

    printf(f, "LI(l,i) = no;\n")
    printf(f, "LJ(l,j) = no;\n\n")

    @translinks.each do |li|
      printf(f, "LI( 'l" + li.id.to_s + "', 'i" + li.supply_site_id.to_s + "') = yes;\n")
      printf(f, "LJ( 'l" + li.id.to_s + "', 'j" + li.demand_site_id.to_s + "') = yes;\n\n")
    end
    printf(f, "\n\n")

    printf(f, "Parameter\n  A(i) /\n")

    @supply_sites.each { |so| printf(f, "i" + so.id.to_s + "  " + so.supply_quantity.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\nN(j) /\n")

    @demand_sites.each { |si| printf(f, "j" + si.id.to_s + "  " + si.demand_quantity.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\nc(l) /\n")

    @translinks.each { |li| printf(f, "l" + li.id.to_s + "  " + li.unit_cost.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, ";\n")
    f.close


    if File.exist?("Transportmengen_v2.txt")
      File.delete("Transportmengen_v2.txt")
    end

    system "C:\\GAMS\\win64\\24.1\\gams Transportmodell_v2"

    flash[:success] = "Optimization started!"
    redirect_to current_user

  end

  def read_transportation_quantities

    if File.exist?("Transportmengen_v2.txt")

      fi=File.open("Transportmengen_v2.txt", "r")
      line=fi.readline
      sa=line.split(" ")
      @objective_function_value=sa[1]
      fi.each { |line| # printf(f,line)
        sa=line.split(";")
        sa0=sa[0].delete "l "
        sa3=sa[3].delete " \n"
        al=Translink.find_by_id(sa0)
        al.transport_quantity=sa3
        al.save
      }
      fi.close

      @translinks = Translink.all

      render "translinks/index"

    else
      flash.now[:not_available] = "Problem not solved!"
      @translinks = Translink.all
      redirect_to translinks_url
    end


  end



  private

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Bitte melden Sie sich an."
    end
  end

end

app/helpers/translinks_helper.rb
module TranslinksHelper
end

app/views/translinks/_form.html.erb
<div class="row">
  <div class="span6 offset3">
<%= form_for(@translink) do |f| %>
    <% if @translink.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@translink.errors.count, "error") %> prohibited this translink from being saved:</h2>

          <ul>
            <% @translink.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label 'Supply Site' %><br />
      <%= f.collection_select :supply_site_id, SupplySite.all, :id, :supply_site_codename %>

    </div>
    <div class="field">
      <%= f.label 'Demand Site' %><br />
      <%= f.collection_select :demand_site_id, DemandSite.all, :id, :demand_site_codename %>
    </div>
    <div class="field">
      <%= f.label 'Transportation Cost' %><br />
      <%= f.text_field :unit_cost %>
    </div>
    <div class="actions">
      <%= f.submit'Save or Update Translink' %>
    </div>
<% end %>
  </div>
</div>


app/views/translinks/edit.html.erb
<h1>Update Translink</h1>

<%= render 'form' %>

<%= link_to 'Show', @translink %><br><br>
<%= link_to 'Back', translinks_path %>

app/views/translinks/index.html.erb
<h1>Data of Translinks</h1>

<% if @objective_function_value!=nil %>
    Objective function value: <b><%=   @objective_function_value %></b><br>   <br>   <br>
<% end %>

<table class="table">
  <tr>
    <th>Supply Site</th>
    <th>Demand Site</th>
    <th>Transportation cost</th>
    <th>Transport Quantity</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @translinks.each do |translink| %>
      <tr>
        <td><%= translink.supply_site.site.codename %></td>
        <td><%= translink.demand_site.site.codename %></td>
        <td><%= translink.unit_cost %></td>
        <td><%= translink.transport_quantity %></td>
        <td><%= link_to 'Show', translink %></td>
        <td><%= link_to 'Change', edit_translink_path(translink) %></td>
        <td><%= link_to 'Destroy', translink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Transportlink', new_translink_path %><br>  <br>
<%= link_to 'Back', current_user %>

app/views/translinks/new.html.erb
<h1>New Translink</h1>

<%= render 'form' %>

<%= link_to 'Back', translinks_path %>

app/views/translinks/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <b>Supply Site</b>
  <%= @supply_site_name  %>
</p>

<p>
  <b>Demand Site</b>
  <%= @demand_site_name %>
</p>

<p>
  <b>Transportation Costs</b>
  <%= @translink.unit_cost %>
</p>

<p>
  <b>Transportation Quantity</b>
  <%= @translink.transport_quantity %>
</p>


<%= link_to 'Change', edit_translink_path(@translink) %> <br><br>
<%= link_to 'Back', translinks_path %>